# Generated by packaging/homebrew/render.sh in the lazyaiden release workflow; do not edit by hand.
class LazyaidenRc < Formula
  desc "LazyGit-style TUI and CLI for the Fellow Aiden coffee brewer"
  homepage "https://github.com/mohammadalijf/lazyaiden"
  version "0.1.0-rc.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0-rc.1/lazyaiden-v0.1.0-rc.1-aarch64-apple-darwin.tar.gz"
      sha256 "f050337d90fc506edcd45d2f05724907be4909b76dfc4808df6a49204f303746"
    end
    on_intel do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0-rc.1/lazyaiden-v0.1.0-rc.1-x86_64-apple-darwin.tar.gz"
      sha256 "318f40c1bfd1ab4171212b1dfd11d59a61380cc74221379d6bfcb2050b0b2587"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0-rc.1/lazyaiden-v0.1.0-rc.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "4e4bf5606a5a6288b16da724cab1d8399caf92219c42a8a038a5acc4cab72657"
    end
    on_intel do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0-rc.1/lazyaiden-v0.1.0-rc.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "ce819478894e774a3901291d605a9aff28a5b2e89e610f1ce99315a833212ed1"
    end
  end

  conflicts_with "lazyaiden", because: "both install the lazyaiden and lazyaiden-cli binaries"

  def install
    bin.install "lazyaiden", "lazyaiden-cli"
    man1.install Dir["man/*.1"]
    %w[lazyaiden lazyaiden-cli].each do |cmd|
      bash_completion.install "completions/#{cmd}.bash" => cmd
      zsh_completion.install "completions/_#{cmd}"
      fish_completion.install "completions/#{cmd}.fish"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyaiden --version")
    assert_match version.to_s, shell_output("#{bin}/lazyaiden-cli --version")
    assert_match "lazyaiden-cli", shell_output("#{bin}/lazyaiden-cli --help")
  end
end
