# Generated by packaging/homebrew/render.sh in the lazyaiden release workflow; do not edit by hand.
class Lazyaiden < Formula
  desc "LazyGit-style TUI and CLI for the Fellow Aiden coffee brewer"
  homepage "https://github.com/mohammadalijf/lazyaiden"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0/lazyaiden-v0.1.0-aarch64-apple-darwin.tar.gz"
      sha256 "774cbe6029fc68df9fb23ef566fec9e417a1f3f749b17c281bed691c57f45763"
    end
    on_intel do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0/lazyaiden-v0.1.0-x86_64-apple-darwin.tar.gz"
      sha256 "62d04bb6e97e998e3c4ea889aeadaa17da1d4aeddc6b31b4b90c01dd0f2248ff"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0/lazyaiden-v0.1.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "2f1842446fb31dec2d8025eafffb8b0114346ee305e674926dea788994af8016"
    end
    on_intel do
      url "https://github.com/mohammadalijf/lazyaiden/releases/download/v0.1.0/lazyaiden-v0.1.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "14af3395e47378cc50b2bc3870aaced368a0610d75592874a458318ca70d5b8a"
    end
  end


  def install
    bin.install "lazyaiden", "lazyaiden-cli"
    man1.install Dir["man/*.1"]
    %w[lazyaiden lazyaiden-cli].each do |cmd|
      bash_completion.install "completions/#{cmd}.bash" => cmd
      zsh_completion.install "completions/_#{cmd}"
      fish_completion.install "completions/#{cmd}.fish"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/lazyaiden --version")
    assert_match version.to_s, shell_output("#{bin}/lazyaiden-cli --version")
    assert_match "lazyaiden-cli", shell_output("#{bin}/lazyaiden-cli --help")
  end
end
